language: go

go:
  - "1.10.1"

env:
  global:
    - SPOTIFY_CLIENT_ID=any
    - SPOTIFY_SECRET=any

script:
  - go build
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)