language: go

go:
  - "1.8"

before_install:
  - go get -v github.com/marcusolsson/tui-go
  - go get -v github.com/zmb3/spotify

script:
  - go build
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)