language: go

go:
  - "1.12"

env:
  global:
    - SPOTIFY_CLIENT_ID=any
    - SPOTIFY_SECRET=any
    - GOMODULES111=on

script:
  - make install_deps
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)